### ISSUE TITLE
如何关闭自动检查更新

### ISSUE THREAD

**Issue by Wiz1code** [cxOrz/chaoxing-sign-cli#2]

**Comment by miaochenxi** [comment]
为了防止学习通代码修改，导致签到无法正常使用，在每次签到运行结束时会强制进行代码拉取，也就是更新。

由于GFW的原因，确实在拉取代码时耗时很长，甚至失败。

如果需要关闭自动更新，请修改项目根目录的 `package.json` 文件，该文件中的 `scripts` 部分如图。

![Screenshot_20211108_111717](https://user-images.githubusercontent.com/32982052/140679170-5b76b63c-50d7-407e-975e-f8fbe64c6fa0.png)

将`scripts`内容修改为如下，将只运行，不更新。

```json
"code": "node ./src/index.js --qrcode",
"loc": "node ./src/index.js --location",
"gen": "node ./src/index.js --general",
"cam": "node ./src/index.js --photo"
```

**Comment by CodeTty** [comment]
感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月8日(星期一) 中午11:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [miaochenxi/chaoxing-sign-cli] 如何关闭自动检查更新 (Issue #2)





 
为了防止学习通代码修改，导致签到无法正常使用，在每次签到运行结束时会强制进行代码拉取，也就是更新。
 
由于GFW的原因，确实在拉取代码时耗时很长，甚至失败。
 
如果需要关闭自动更新，请修改项目根目录的 package.json 文件，该文件中的 scripts 部分如图。
 

 
将scripts内容修改为如下，将只运行，不更新。
 "code": "node ./src/index.js --qrcode", "loc": "node ./src/index.js --location", "gen": "node ./src/index.js --general", "cam": "node ./src/index.js --photo"
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DUXING130** [comment]
在1.8.1版本中如何修改package.json可以让它不再显示更新而不用按Ctrl+C?

**Comment by DUXING130** [comment]
因为在我试图用老方法停止更新时，导致不能运行这

**Comment by miaochenxi** [comment]
> 因为在我试图用老方法停止更新时，导致不能运行这

和老方法一样修改。不能运行的情况，不应该出现。仔细检查是否修改正确

**Comment by DUXING130** [comment]
> 

已确认一致，但依然会在出现
> chaoxing-sign-cli@1.8.1 gen
> (node ./src/index.js --general
后，中止

**Comment by miaochenxi** [comment]
> > 
> 
> 已确认一致，但依然会在出现
> > chaoxing-sign-cli@1.8.1 gen
> > (node ./src/index.js --general
> 后，中止

麻烦提供一下完整截图吧

**Comment by DUXING130** [comment]
![image](https://user-images.githubusercontent.com/95281874/144029953-ab81570c-333b-4f04-b78a-4de096c46b33.png)
如图

**Comment by DUXING130** [comment]
抱歉错图
![image](https://user-images.githubusercontent.com/95281874/144030143-ec86d1eb-d2fc-46c9-9887-47cdd9d6c819.png)

**Comment by miaochenxi** [comment]
> 抱歉错图
> ![image](https://user-images.githubusercontent.com/95281874/144030143-ec86d1eb-d2fc-46c9-9887-47cdd9d6c819.png)
> 

很明显你在命令前多加了一个左括号

**Comment by DUXING130** [comment]
哦抱歉，没注意到左面的

**Comment by qyspring** [comment]
为啥突然修改命令啊
没签上

**Comment by miaochenxi** [comment]
> 为啥突然修改命令啊 没签上

原本的太麻烦了费时间，有些同学还想不起来命令，干脆就合并成一个命令，自动检测。
